feat :  add electron auto update template
electron-vite/electron-vite-react pull request #117
Opened 2023-02-27 02:48 UTC by RSS1102

feat : add some components
url : https://github.com/RSS1101/electron-vite-react

2023-02-27 03:07 UTC, caoxiemeihao requested changes
Thanks PR!
I think there are a few things that need to be improved.

1. Use English comments of  i18n.
2. Code style.

2023-02-27 03:07 UTC, caoxiemeihao commented on src/components/RsModal/index.scss
> +.rs-modal-bg{
What is `Rs xxx` and what does it mean?

2023-02-27 03:09 UTC, RSS1102 commented on src/components/RsModal/index.scss
> +.rs-modal-bg{
-.- 啊这，这是我之前自己写的组件，我忘了改名字

2023-02-27 03:10 UTC, RSS1102 commented on src/App.tsx
> +import Update from "./pages/update"
ok

2023-02-27 03:10 UTC, RSS1102 commented on package.json
> +    "electron-updater": "^5.3.0"
ok

2023-02-27 03:10 UTC, RSS1102 commented on electron/preload/update.ts
> +import { autoUpdater } from "electron-updater"
get

2023-02-27 03:12 UTC, RSS1102 commented on electron-builder.json5
> +    url: 'https://github.com/RSS1101/electron-vite-react/releases/download/v9.9.9/',
你是要自己打包一个程序用来更新他吗？
或者说你要打算将某一个版本releases放入更新程序（.exe）嘛？

2023-02-27 03:43 UTC, caoxiemeihao commented on electron-builder.json5
> +    url: 'https://github.com/RSS1101/electron-vite-react/releases/download/v9.9.9/',
要么用组织链接打个包，要么这里空着给用户自己配置可好？

2023-02-27 03:47 UTC, RSS1102 commented on electron-builder.json5
> +    url: 'https://github.com/RSS1101/electron-vite-react/releases/download/v9.9.9/',
> 要么用组织链接打个包，要么这里空着给用户自己配置可好？
我个人认为还是打包一个出来，至少让用户在运行这个项目的时候就知道这个更新功能的可行性。
1，要么组织新创建一个repo用来单独存放更新下载的包。
2，要么可以在当前repo内创建一个新的releases存放下载包。

2023-02-28 02:04 UTC, RSS1102 commented on src/components/RsModal/index.scss
> +.rs-modal-bg{
为了避免样式冲突，将css的前缀添加了 up-xxx，组件命名已更改。

2023-02-28 02:06 UTC, RSS1102 commented on electron-builder.json5
> +    url: 'https://github.com/RSS1101/electron-vite-react/releases/download/v9.9.9/',
关于更新连接，有怎么样的一个主意呢？

2023-02-28 06:41 UTC, caoxiemeihao commented on src/components/RsModal/index.scss
> +.rs-modal-bg{
> 为了避免样式冲突，将css的前缀添加了 up-xxx，组件命名已更改。

也可以的，还有种 Vite 原生就支持的 css module 方案。

2023-02-28 06:42 UTC, caoxiemeihao commented on electron-builder.json5
> +    url: 'https://github.com/RSS1101/electron-vite-react/releases/download/v9.9.9/',
用组织的链接打个包咯 ⊙∀⊙

2023-02-28 06:44 UTC, RSS1102 commented on electron-builder.json5
> +    url: 'https://github.com/RSS1101/electron-vite-react/releases/download/v9.9.9/',
> 用组织的链接打个包咯 ⊙∀⊙
第一种？两者都可，如果用第一种的话，你拉个新的repo，仓库代码直接放个`README.md`即可.发个9.9.9的releases.

2023-02-28 06:55 UTC, caoxiemeihao commented on electron-builder.json5
> +    url: 'https://github.com/RSS1101/electron-vite-react/releases/download/v9.9.9/',
https://github.com/electron-vite/electron-vite-react/releases/tag/v0.9.9

试试这个呢

2023-02-28 08:51 UTC, RSS1102 commented on package.json
> +    "electron-updater": "^5.3.0"
当`electron-updater` 在`devDependencies`里时：
![image](https://user-images.githubusercontent.com/81673017/221801490-997f9de0-773c-4e97-8252-0aa31d59265c.png)
![image](https://user-images.githubusercontent.com/81673017/221801708-fe98bfc2-4a5e-4d81-a54d-ea492a5c2fcd.png)

2023-02-28 08:51 UTC, RSS1102 commented on electron-builder.json5
> +    url: 'https://github.com/RSS1101/electron-vite-react/releases/download/v9.9.9/',
可

2023-03-09 09:39 UTC, closed without merging